# Generated by Django 3.2.12 on 2022-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebookapi', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
    ]
